### ISSUE TITLE
Using multiple processes for parallelising computations

### ISSUE THREAD

**Issue by danieljfarrell** [danieljfarrell/pvtrace#18]
Using https://docs.python.org/3/library/concurrent.futures.html

**Comment by danieljfarrell** [comment]
To-do. Make an example showing how to do this based on the hello world

**Comment by jaydeshpande** [comment]
This may be relevant too: https://numba.pydata.org/numba-doc/0.11/prange.html 

This may come in handy for larger and more complex traces: https://numba.pydata.org/numba-doc/0.13/CUDAJit.html

**Comment by danieljfarrell** [comment]
It would be excellent to have a CUDA enabled ray-tracing algorithm in pvtrace. I think it would be a major rewrite though. We would have to spawn something like a million rays from a light source and somehow apply all the current logic across all the rays in the bundle. I can't quite see how that would all hang together at the moment.

**Comment by danieljfarrell** [comment]
This is now implemented in the CLI
