### ISSUE TITLE
Test install on Linux

### ISSUE THREAD

**Issue by danieljfarrell** [danieljfarrell/pvtrace#34]
Some problems have been reported install on Ubuntu.

**Comment by BrightLamp** [comment]
I have tried installing pvtrace in some ways, both on Windows 10x64 and Ubuntu 16.04/18.04, conda env and virtualenvwrapper env failed many times.
Howerver, on the base env of Anaconda3-2020.02, installation is always successful, both on Windows 10x64 and Ubuntu 16.04/18.04.

**Comment by danieljfarrell** [comment]
Thanks so much for the tips! Yes, there is a problem with the dependencies with RTree on platforms other than MacOS.

I will update the README with this information.

Glad you are finding it useful! How are you using it?

**Comment by danieljfarrell** [comment]
README has been updated with conda instructions that work on Linux and Windows
